### ISSUE TITLE
更正

### ISSUE THREAD

**Issue by RuiSama7457** [Cai1Hsu/osu-Hosts#1]
原来的cloudflare优选用不了，这个复制到文件夹中再打开可以用
https://github.com/XIU2/CloudflareSpeedTest

**Comment by Cai1Hsu** [comment]
感谢反馈，我已经用[CloudflareSpeedTest](https://github.com/XIU2/CloudflareSpeedTest)最新的release版本替换了release里原来的文件，但是我没有亲自测试过能否正常使用。本项目只是我以前过渡时期临时使用的，因此不会受到持续维护。

我要说明的是，使用Hosts这种方法存在很多弊端，比如每次更新IP源需要较长时间，需要手动刷新DNS缓存，而且需要频繁更新IP源。更好的方法是使用[microsoft/reverse-proxy](https://github.com/microsoft/reverse-proxy)进行本地反代，或者一劳永逸地用梯子。
